[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r backend/requirements.txt"]

[phases.start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
